[tool.poetry]
name = "crea-therapy"
version = "0.1.0"
description = ""
authors = ["Gabriel Soler <gsoler@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
coltrane = "^0.33.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
